name: Build alma9-spack docker image

on:
  schedule:
    - cron: "0 0 * * 0"

  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths:
      - dockerfiles/alma9-spack-base.dockerfile

  workflow_dispatch:

jobs:

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Check out the repo
        uses: actions/checkout@main
        with:
          repository: art-daq/daq-docker
          path: daq-docker 
      
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GHIO }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            eflumerf/alma9-spack
            ghcr.io/art-daq/alma9-spack
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag
      
      - name: prepare build dir
        run: |
          build_dir="${{ github.workspace }}/docker-build"
          mkdir -p $build_dir
          cd $build_dir
          cp ${{ github.workspace }}/daq-docker/dockerfiles/alma9-spack-base.dockerfile $build_dir/Dockerfile
      
      - name: Build and push Docker images
        uses: docker/build-push-action@master
        with:
          context: ${{ github.workspace }}/docker-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
