name: Build docker image with externals

on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:

  build_sl7_externals:
    name: build_sl7
    runs-on: [self-hosted]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GHIO }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/art-daq/sl7-externals
          tags: |
            type=raw,value=latest

      - name: prepare build dir
        id: prep_build_dir
        run: |
          build_dir="/home/eflumerf/cvmfs_artdaq"
          cd $build_dir
          refresh_date=$(date +%y-%m-%d)
          echo "FROM ghcr.io/art-daq/sl7:latest" > Dockerfile
          echo 'MAINTAINER Pengfei Ding "dingpf@fnal.gov"' >> Dockerfile
          echo "ENV REFRESHED_AT $refresh_date" >> Dockerfile
          echo "ADD https://raw.githubusercontent.com/art-daq/otsdaq_demo/develop/tools/quick-mrb-start.sh /" >> Dockerfile
          echo "RUN /quick_mrb_start.sh" >> Dockerfile
          echo 'ENTRYPOINT ["/bin/bash"]' >> Dockerfile

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: /home/eflumerf/cvmfs_artdaq
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up
        if: always()
        run: |

            rm -f /home/eflumerf/cvmfs_artdaq/Dockerfile
            docker image prune -f
            docker container prune -f
            docker network prune -f
            docker volume prune -f

  push_sl7_externals_to_dockerhub:
    name: push_sl7_ext_dockerhub
    runs-on: ubuntu-latest
    needs: build_sl7_externals
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to dockerhub
        run: |
          docker pull ghcr.io/art-daq/sl7-externals:latest
          docker tag ghcr.io/art-daq/sl7-externals:latest eflumerf/sl7-externals:latest
          docker push eflumerf/sl7-externals:latest
