name: Build sl7 docker image

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
    paths:
      - dockerfiles/sl7.dockerfile

  workflow_dispatch:

jobs:

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: DUNE-DAQ/daq-docker
          path: daq-docker 
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            dunedaq/sl7
            ghcr.io/DUNE-DAQ/sl7
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag

      - name: prepare build dir
        run: |
          build_dir="${{ github.workspace }}/docker-build"
          mkdir -p $build_dir
          cd $build_dir
          cp ${{ github.workspace }}/daq-docker/dockerfiles/sl7.dockerfile $build_dir/Dockerfile
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/docker-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
